name: Build Memos-FreeBSD

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Memos-FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Build Memos-FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y node npm wget curl git go121 gcc bash gawk gsed
          ln -s /usr/local/bin/go121 /usr/local/bin/go
        run: |
          export LATEST_APP=v0.18.2
          git clone --branch $LATEST_APP https://github.com/usememos/memos.git memosfreebsd
          cd memosfreebsd/
          go build -o memosfreebsd ./bin/memos/main.go
          cd ..

    - name: Generate release tag
      id: tag
      run: echo "release_tag=v0.18.2" >> $GITHUB_OUTPUT

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: Release ${{ steps.tag.outputs.release_tag }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
           memosfreebsd/memosfreebsd
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'SinzMise/memos-deploy'
        retain_days: 1
        keep_minimum_runs: 8
