name: Build Memos-FreeBSD

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Memos-FreeBSD
    steps:
    - uses: actions/checkout@v4

    - name: Set Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Make Memos-Web
      run: |
          export LATEST_APP=v0.18.2
          git clone --branch $LATEST_APP https://github.com/usememos/memos.git memos
          cd memos/web
          pnpm i --frozen-lockfile
          pnpm type-gen
          pnpm build
          cd ..
          mv -f "./web/dist" "./server/"
    
    - name: Build Memos-FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y node npm wget curl git go121 gcc bash gawk gsed
          ln -s /usr/local/bin/go121 /usr/local/bin/go
        run: |
          cd memos
          go mod tidy
          go build -o memos-freebsd ./bin/memos/main.go
          cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: Memos-FreeBSD
        path: |
            memos/memos-freebsd

    - name: Generate release tag
      id: tag
      run: echo "release_tag=v0.18.2" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              memos/memos-freebsd
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'SinzMise/memos-deploy'
        retain_days: 1
        keep_minimum_runs: 8
