name: Run Tests

on:
  schedule:
    - cron: '0 16 */1 * *'
  workflow_dispatch:

env:
  GITHUB_NAME: ${{ secrets.GH_NAME }} # 你的github昵称
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }} # 你的github邮箱
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # github token

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compare versions
        run: |
          export REMOTEVERSION=$(wget -qO- https://api.github.com/repos/usememos/memos/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          export LOCALVERSION=$(curl --location --silent --fail --show-error "https://api.github.com/repos/SinzMise/memos-deploy/releases/latest" | grep -oP '"tag_name":\s*"\K[^"]+')
          bash compare.sh

      - name: Trigger release（FreeBSD）
        if: ${{ env.SYNCED == 0 }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              await github.rest.actions.createWorkflowDispatch({
              owner: 'SinzMise',
              repo: 'memos-deploy',
              workflow_id: 'build-freebsd.yml',
              ref: 'master'
              })
              
      - name: Delete workflow runs
        if: ${{ env.SYNCED == 1 }}
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'SinzMise/memos-deploy'
          retain_days: 1
          keep_minimum_runs: 8
